---
title: "Population Evolution Simulator"
author: "Paul Sabharwal"
runtime: shiny
output: html_document
---

```{r, include = F}
library(tidyverse)
library(shiny)
```


# Single population selection and mutation simulation.

```{r shiny-input,echo=F}
fluidRow(
  column(6,
         numericInput("gens","number of generations",100,width = "auto")),
  column(6,
         numericInput("fitAA","fitness of AA",1,width = "auto"))
)
fluidRow(
  column(6,
         numericInput("muts","Mutation rate (symmetric)",0,width = "auto")),
  column(6,
         numericInput("fitAa","fitness of Aa",1,width = "auto"))
)
fluidRow(
  column(6,
         sliderInput("pA0", label = "p(A):",
              min = 0, max = 1, value = 0.5, step = 0.001,width = "auto")),
  column(6,
         numericInput("fitaa","fitness of aa",1,width = "auto"))
)
```

```{r calc-1,echo=F}
next_gen <- function(gen_table,fAA,fAa,faa,mut){
  
  num <- nrow(gen_table)
  
  last <- gen_table %>% slice(num)
  
  old_AA <- last %>% pull(AA)
  old_Aa <- last %>% pull(Aa)
  old_aa <- last %>% pull(aa)
  
  new_AA <- old_AA * fAA
  new_Aa <- old_Aa * fAa
  new_aa <- old_aa * faa
  total <- new_AA + new_Aa + new_aa
  new_AA <- new_AA / total
  new_Aa <- new_Aa / total
  new_aa <- new_aa / total
  
  new_pA <- (2*new_AA + new_Aa) / 2
  dA_mut <- (1-new_pA)*mut - new_pA*mut
  new_pA <- new_pA + dA_mut
  
  new_AA <- new_pA^2
  new_Aa <- 2*new_pA*(1-new_pA)
  new_aa <- (1-new_pA)^2
  
  old_gen <- last %>% pull(Gen)
  new_table <- gen_table %>%
    add_row(Gen = old_gen+1, AA = new_AA, Aa = new_Aa, aa = new_aa,pA = new_pA)
  return(new_table)
}
```


```{r shiny-render-1,echo=F}
renderPlot({
  init_A <- input$pA0
  init_AA <- init_A^2
  init_Aa <- 2*init_A*(1-init_A)
  init_aa <- (1-init_A)^2

  fit_AA <- input$fitAA
  fit_Aa <- input$fitAa
  fit_aa <- input$fitaa
  
  mut_rate <- input$muts
  num_gens <- input$gens
  
  gen_table <- tibble("Gen"=1,"AA"=init_AA,"Aa"=init_Aa,"aa"=init_aa,"pA"=init_A)
  
  for(i in 1:num_gens){
    gen_table <- next_gen(gen_table,fit_AA,fit_Aa,fit_aa,mut_rate)
  }
  
  ggplot(gen_table,aes(Gen,pA)) +
    geom_line()+
    ylim(0,1)
})
```

## Two populations with migration and selection

```{r shiny-input-2,echo=F}
fluidRow(
  column(6,
         sliderInput("pA0_1", label = "p(A) in Pop 1:",
              min = 0, max = 1, value = 0.5, step = 0.001,width = "auto")),
  column(6,
         sliderInput("pA0_2", label = "p(A) in Pop 2:",
              min = 0, max = 1, value = 0.5, step = 0.001,width = "auto"))
)
fluidRow(
  column(6,
         numericInput("gens_2","number of generations",100,width = "auto")),
  column(6,
         numericInput("migrate","migration rate:",0.01,width = "auto"))
)
fluidRow(
  column(4,
         numericInput("fitAA_1","fitness of AA in Pop 1",1)),
  column(4,
         numericInput("fitAa_1","fitness of Aa in Pop 1",1)),
  column(4,
         numericInput("fitaa_1","fitness of aa in Pop 1",1))
)
fluidRow(
  column(4,
         numericInput("fitAA_2","fitness of AA in Pop 2",1)),
  column(4,
         numericInput("fitAa_2","fitness of Aa in Pop 2",1)),
  column(4,
         numericInput("fitaa_2","fitness of aa in Pop 2",1))
)
```

```{r calc-2,echo=F}
next_gen_2 <- function(gen_table,fAA_1,fAa_1,faa_1,fAA_2,fAa_2,faa_2,migrate){
  
  num <- nrow(gen_table)
  last_1 <- gen_table %>% slice(num-1)
  last_2 <- gen_table %>% slice(num)
  
  # calc pop 1
  old_AA_1 <- last_1 %>% pull(AA)
  old_Aa_1 <- last_1 %>% pull(Aa)
  old_aa_1 <- last_1 %>% pull(aa)
  
  new_AA_1 <- old_AA_1 * fAA_1
  new_Aa_1 <- old_Aa_1 * fAa_1
  new_aa_1 <- old_aa_1 * faa_1
  total_1 <- new_AA_1 + new_Aa_1 + new_aa_1
  new_AA_1 <- new_AA_1 / total_1
  new_Aa_1 <- new_Aa_1 / total_1
  new_aa_1 <- new_aa_1 / total_1
  
  new_pA_1 <- (2*new_AA_1 + new_Aa_1) / 2
  
  new_AA_1 <- new_pA_1^2
  new_Aa_1 <- 2*new_pA_1*(1-new_pA_1)
  new_aa_1 <- (1-new_pA_1)^2
  
  # calc pop 2
  old_AA_2 <- last_2 %>% pull(AA)
  old_Aa_2 <- last_2 %>% pull(Aa)
  old_aa_2 <- last_2 %>% pull(aa)
  
  new_AA_2 <- old_AA_2 * fAA_2
  new_Aa_2 <- old_Aa_2 * fAa_2
  new_aa_2 <- old_aa_2 * faa_2
  total_2 <- new_AA_2 + new_Aa_2 + new_aa_2
  new_AA_2 <- new_AA_2 / total_2
  new_Aa_2 <- new_Aa_2 / total_2
  new_aa_2 <- new_aa_2 / total_2
  
  new_pA_2 <- (2*new_AA_2 + new_Aa_2) / 2
  
  new_AA_2 <- new_pA_2^2
  new_Aa_2 <- 2*new_pA_2*(1-new_pA_2)
  new_aa_2 <- (1-new_pA_2)^2
  
  # do migration
  temp_AA_1 <- new_AA_1
  temp_Aa_1 <- new_Aa_1
  temp_aa_1 <- new_aa_1
  
  new_AA_1 <- new_AA_1 + migrate*new_AA_2 - migrate*new_AA_1
  new_Aa_1 <- new_Aa_1 + migrate*new_Aa_2 - migrate*new_Aa_1
  new_aa_1 <- new_aa_1 + migrate*new_aa_2 - migrate*new_aa_1
  
  new_AA_2 <- new_AA_2 + migrate*temp_AA_1 - migrate*new_AA_2
  new_Aa_2 <- new_Aa_2 + migrate*temp_Aa_1 - migrate*new_Aa_2
  new_aa_2 <- new_aa_2 + migrate*temp_aa_1 - migrate*new_aa_2
  
  
  old_gen <- last_1 %>% pull(Gen)
  new_table <- gen_table %>%
    add_row(Gen=old_gen+1,AA=new_AA_1,Aa=new_Aa_1,aa=new_aa_1,pA=new_pA_1,pop=1) %>%
    add_row(Gen=old_gen+1,AA=new_AA_2,Aa=new_Aa_2,aa=new_aa_2,pA=new_pA_2,pop=2)
    
  return(new_table)
}
```


```{r shiny-render-2,echo=F}
renderPlot({
  init_A_1 <- input$pA0_1
  init_AA_1 <- init_A_1^2
  init_Aa_1 <- 2*init_A_1*(1-init_A_1)
  init_aa_1 <- (1-init_A_1)^2

  fit_AA_1 <- input$fitAA_1
  fit_Aa_1 <- input$fitAa_1
  fit_aa_1 <- input$fitaa_1
  
  init_A_2 <- input$pA0_2
  init_AA_2 <- init_A_2^2
  init_Aa_2 <- 2*init_A_2*(1-init_A_2)
  init_aa_2 <- (1-init_A_2)^2

  fit_AA_2 <- input$fitAA_2
  fit_Aa_2 <- input$fitAa_2
  fit_aa_2 <- input$fitaa_2
  
  num_gens_2 <- input$gens_2
  mig_rate <- input$migrate
  
  gen_table_2 <- tibble("Gen"=c(1,1),
                      "AA"=c(init_AA_1,init_AA_2),
                      "Aa"=c(init_Aa_1,init_Aa_2),
                      "aa"=c(init_aa_1,init_aa_2),
                      "pA"=c(init_A_1,init_A_2),
                      "pop"=c(1,2))
  
  for(i in 1:num_gens_2){
    gen_table_2 <- next_gen_2(gen_table_2,fit_AA_1,fit_Aa_1,fit_aa_1,
                              fit_AA_2,fit_Aa_2,fit_aa_2,mig_rate)
  }
  
  print(mig_rate)
  print(gen_table_2)
  
  ggplot(gen_table_2,aes(Gen,pA)) +
    geom_line() + 
    facet_wrap(~ pop) +
    ylim(0,1)
})
```
